# The code below, allowing automated tests on PRs to the main branch, was retrieved and tweaked from: https://stevekinney.net/courses/testing/continuous-integration
# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install ionic for the cli
        run: npm install -g @ionic/cli
        
      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test.unit

      - name: Start ionic server
        run: ionic serve
        
      - name: Run e2e tests
        run: npm run test.e2e
